function m(c,a,b,d){c.h.ia(c.X,a,b,d)}function p(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Jb()._OnMessageFromDOM({type:"event",component:c.X,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function q(c,a,b){c.h.i(c.X,a,b)}function aa(c,a){for(const [b,d]of a)q(c,b,d)}window.ua=class{constructor(c,a){this.h=c;this.X=a}Ua(){}};window.sc=class{constructor(){}};"use strict";class ba{constructor(c){this.Y=c;this.Fa=!1;this.Ia=!0;this.Z=this.v=this.Ra=-1}}
function ca(c,a){const b=a.elementId,d=c.sa(b,a),e=new ba(d);c.F.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ia=!!a.isVisible;var f=c.ya(d);f.addEventListener("focus",()=>{da(c,"elem-focused",b)});f.addEventListener("blur",()=>{da(c,"elem-blurred",b)});f=a.htmlIndex;e.Ra=f;e.Z=a.htmlZIndex;c.J&&(a=c.h.va(f),e.v=a,c.h.R(a).appendChild(d))}function u(c,a,b){q(c,a,d=>{const e=v(c,d.elementId);return b(e,d)})}
function v(c,a){c=c.F.get(a);if(!c)throw Error(`no element with id ${a}`);return c.Y}function da(c,a,b){var d;d||(d={});d.elementId=b;m(c,a,d)}function w(c,a,b,d){d||(d={});d.elementId=b;p(c,a,d)}
window.ha=class extends self.ua{constructor(c,a){super(c,a);this.F=new Map;this.J=!0;aa(this,[["create",b=>ca(this,b)],["destroy",b=>{b=b.elementId;const d=v(this,b);this.J&&d.parentElement.removeChild(d);this.F.delete(b)}],["set-visible",b=>{if(this.J){var d=this.F.get(b.elementId),e=d.Y;d.Fa?e.style.display=b.isVisible?"":"none":d.Ia=!!b.isVisible}}],["update-position",b=>{if(this.J){var d=this.F.get(b.elementId),e=d.Y,f=this.h;e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+
"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.Ra=h;h=f.va(h);h!==d.v&&(e.remove(),f.R(h).appendChild(e),d.v=h,f.Ca());b=b.htmlZIndex;b!==d.Z&&(d.Z=b,f.Ca());d.Fa||(d.Fa=!0,d.Ia&&(e.style.display=""))}}],["update-state",b=>{const d=v(this,b.elementId);this.ja(d,b)}],["focus",b=>{const d=this.ya(v(this,b.elementId));b.focus?d.focus():d.blur()}],["set-css-style",b=>{const d=v(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,
b):d.style[e]=b}],["set-attribute",b=>{v(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{v(this,b.elementId).removeAttribute(b.name)}]]);u(this,"get-element",b=>b)}sa(){throw Error("required override");}ja(){throw Error("required override");}ya(c){return c}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ia=0;function y(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.ic?new Promise(b=>{const d="c3_resolve_"+ia;++ia;self[d]=b;a.textContent=c.mc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ja(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let z=new Audio;
const ka={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function la(c){c=await ma(c);return(new TextDecoder("utf-8")).decode(c)}
function ma(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const A=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,E=new Map;let na=0;const oa=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");oa.push(c)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.U=class c{constructor(a){this.m=a.oc;this.ba=null;this.l="";this.M=a.lc;this.ea={};this.Ka=this.O=null;this.K=[];this.G=null;this.ob=!0;this.j=[];this.Oa=[];this.Pa=!1;this.qb=()=>this.Hb();this.nb=!1;this.$=null;this.L=-1;this.dc=()=>this.Sb();this.ca=new Set;this.Sa=null;this.rb=[];this.g=a.sb;this.Ha="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;fa&&(this.m=!1);if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.H()?self.chrome.webview.addEventListener("message",b=>this.fb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.fb(b));this.ma=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Wb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Nb());this.i("runtime","cordova-fetch-local-file",b=>this.Ob(b));this.i("runtime","create-job-worker",()=>this.Pb());this.i("runtime","send-wrapper-extension-message",b=>this.Vb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.cb(a)):this.cb(a)}ub(){return this.j[0].canvas}va(a){return Math.min(a,this.j.length-1)}R(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].fa}_GetHTMLWrapElement(a){return this.R(a)}yb(){return ea&&
"cordova"===this.g}T(){const a=navigator.userAgent;return ea&&pa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}wb(){return x}Wa(){return x&&pa.has(this.g)}Xa(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}H(){return this.Xa()||"xbox-uwp-webview2"===this.g}async cb(a){this.m&&!await ja()&&(this.m=!1);"macos-wkwebview"===this.g?this.V({type:"ready"}):this.H()&&(this.Zb(),this.rb=(await this.Mb()).registeredComponentIds);
if("playable-ad"===this.g){this.A=self.c3_base64files;this.ma={};await this.Eb();for(let d=0,e=a.P.length;d<e;++d){var b=a.P[d];this.ma.hasOwnProperty(b)?a.P[d]={ic:!0,mc:this.ma[b]}:this.A.hasOwnProperty(b)&&(a.P[d]=URL.createObjectURL(this.A[b]))}a.qa=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ya(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.kc?this.l=a.kc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.qc&&(this.ea=a.qc);b=new MessageChannel;this.ba=b.port1;this.ba.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Rb(d));this.$=new self.zb(this);await ra(this.$);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Lb(a,b.port2):await this.Kb(a,b.port2)}za(a){a=this.ea.hasOwnProperty(a)?this.ea[a]:a.endsWith("/workermain.js")&&this.ea.hasOwnProperty("workermain.js")?this.ea["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ta(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ha)return a=await this.ra(d.hc?a:this.M+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}u(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}wa(){return this.H()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}bb(a){var b=this.l,d=location.href,e=this.u(),f=this.o(),h=this.wa(),g=window.devicePixelRatio,k=c.S(),l=a.vc,n=window.cr_previewImageBlobs||this.A,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,Da=window.cr_swClientId||"";a=a.sb;var Ea=(new URLSearchParams(self.location.search)).has("debug"),P=this.$;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:Da,exportType:a,isDebug:Ea,ife:!!self.uc,jobScheduler:{inputPort:P.Ga,outputPort:P.Na,maxNumWorkers:P.bc},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.M+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.M+"opus.wasm.wasm",isFileProtocol:this.Ha,isiOSCordova:this.yb(),isiOSWebView:this.T(),
isWindowsWebView2:this.Xa(),isAnyWebView2Wrapper:this.H(),wrapperComponentIds:this.rb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Lb(a,b){const d=this.za(a.pc);"preview"===this.g?(this.O=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const r=t=>{this.O.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():n()};this.O.addEventListener("message",r);this.O.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.O=await this.ta(d,this.l,{type:"module",name:"Runtime",hc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,fa:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.qa||[],k=a.P;g=await Promise.all(g.map(l=>this.I(l)));k=await Promise.all(k.map(l=>this.I(l)));
if("cordova"===this.g)for(let l=0,n=a.pa.length;l<n;++l){const r=a.pa[l],t=r[0];if(t===a.Ta||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.I(t)}this.O.postMessage(Object.assign(this.bb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.pa,mainProjectScript:a.Ta,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...sa(this.$)]);this.K=C.map(l=>new l(this));this.ab();F(e);G(h);ta(this.G);self.c3_callFunction=
(l,n)=>{var r=this.G;return r.h.Ab(r.X,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ia("runtime","go-to-last-error-script"))}async Kb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,fa:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.K=C.map(g=>new g(this));this.ab();
F(d);G(e);e=a.P.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.qa)){var f=[...a.qa].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.I(g)));await Promise.all(e.map(g=>y(g)));e=self.C3_ProjectScriptsStatus;f=a.Ta;const h=a.pa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.I(k),await y(k),"preview"!==this.g||e[g]||this.gb(g,"main script did not run to completion")}catch(l){this.gb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.I(k),await y(k);"preview"===this.g&&"object"!==typeof self.rc.tc?(this.la(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.bb(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:oa}),ta(this.G),this.eb(),this.Ka=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Ka,a))}gb(a,b){this.la();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}eb(){this.la()}la(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Pb(){const a=await va(this.$);return{outputPort:a,transferables:[a]}}Wb(a){if(!this.nb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,fa:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.ob&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.ob=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,fa:n}=this.j.pop();n.remove();this.m&&!d?this.Oa.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,F(b),G(d),this.j.push({canvas:b,fa:d});for(const l of this.K)if(l instanceof window.ha&&l.J)for(const n of l.F.values())e=l.h.va(n.Ra),f=n.v,-1!==e&&-1!==f&&e!==f&&(f=n.Y,f.remove(),l.h.R(e).appendChild(f),n.v=e);this.Ca();return{addedCanvases:a,transferables:k}}Nb(){for(const a of this.Oa)a.remove();this.Oa.length=0}Ca(){this.Pa||(this.Pa=!0,this.Ya(this.qb))}Hb(){this.Yb(this.qb);
this.Pa=!1;let a=[];for(var b of this.K)if(b instanceof window.ha){var d=b.J?[...b.F.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.v,l=g.v;return k!==l?k-l:h.Z-g.Z});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.v!==b&&(this.$a(b,a.slice(d,e)),b=h.v,d=e)}d<e&&this.$a(b,a.slice(d,e))}$a(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.Y);var d=new Set(b);a=this.R(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=
f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Jb(){if(this.m)throw Error("not available in worker mode");return this.Ka}ia(a,b,d,e){this.ba.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Ab(a,b){const d=na++,e=new Promise((f,h)=>{E.set(d,{resolve:f,reject:h})});this.ba.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;
if("event"===b)return this.Qb(a);if("result"===b)this.Tb(a);else if("runtime-ready"===b)this.Ub();else if("alert-error"===b)this.la(),alert(a.message);else if("creating-runtime"===b)this.eb();else throw Error(`unknown message '${b}'`);}Qb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ka(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ka(f,!0,
g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ka(f,!1,""+g)}):this.ka(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ka(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.ba.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Tb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=E.get(b);d?e.resolve(a):e.reject(a);E.delete(b)}i(a,b,d){let e=D.get(a);e||(e=new Map,
D.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static ga(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}ab(){for(const a of this.K)if("runtime"===a.X){this.G=a;return}throw Error("cannot find runtime DOM handler");}Rb(a){this.ia("debugger","message",a)}Ub(){for(const a of this.K)a.Ua()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static hb(a){qa=!!a}Ya(a){this.ca.add(a);
this.Ba()}Yb(a){this.ca.delete(a);0===this.ca.size&&this.Za()}Ba(){-1===this.L&&0<this.ca.size&&(this.L=requestAnimationFrame(this.dc))}Za(){-1!==this.L&&(cancelAnimationFrame(this.L),this.L=-1)}Sb(){this.L=-1;for(const a of this.ca)a();this.Ba()}Aa(){this.G.Aa()}Bb(){this.nb=!0}vb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}xb(a){return!this.vb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ha&&this.xb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.ra(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ob(a){const b=a.filename;switch(a.as){case "text":return await this.tb(b);case "buffer":return await this.ra(b);default:throw Error("unsupported type");}}Va(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async tb(a){a=await this.Va(a);return await la(a)}xa(){if(A.length&&!(8<=B)){B++;
var a=A.shift();this.Fb(a.filename,a.nc,a.fc)}}ra(a){return new Promise((b,d)=>{A.push({filename:a,nc:e=>{B--;this.xa();b(e)},fc:e=>{B--;this.xa();d(e)}});this.xa()})}async Fb(a,b,d){try{const e=await this.Va(a),f=await ma(e);b(f)}catch(e){d(e)}}fb(a){if("entered-fullscreen"===a)c.hb(!0),H(this.G);else if("exited-fullscreen"===a)c.hb(!1),H(this.G);else if("object"===typeof a){const b=a.type;"directory-handles"!==b&&("wrapper-init-response"===b?(this.Sa(a),this.Sa=null):"extension-message"===b?this.ia("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Vb(a){this.V({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}V(a){this.H()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Zb(){window.moveTo=(a,b)=>{this.V({type:"set-window-position",windowX:Math.ceil(a),
windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.V({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Mb(){return this.H()?new Promise(a=>{this.Sa=a;this.V({type:"wrapper-init"})}):Promise.resolve()}async Eb(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.Db(b,d));await Promise.all(a)}async Db(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.ma[a]=b.str;else{let d=await this.Ib(b);d||(d=this.Gb(b));this.A[a]=d}}async Ib(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Gb(a){a=this.Xb(a);return this.Cb(a.data,a.jc)}Xb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{jc:a,data:d}}Cb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const I=self.U,wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},K={dispatchUserScriptEvent:!0},L={dispatchRuntimeEvent:!0};function xa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function ya(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function za(c){c=URL.createObjectURL(c);try{return await ya(c)}finally{URL.revokeObjectURL(c)}}function Aa(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const Ba=new Set(["input","textarea","datalist","select"]),Ca=new Set(["canvas","body","html"]);
function M(c){c.target.tagName&&Ca.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function N(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Fa(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await za(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await za(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let O=!1;document.addEventListener("pause",()=>O=!0);document.addEventListener("resume",()=>O=!1);function F(c){c.addEventListener("selectstart",M);c.addEventListener("gesturehold",M);c.addEventListener("pointerdown",M)}function G(c){c.addEventListener("selectstart",N);c.addEventListener("gesturehold",N);c.addEventListener("touchstart",N)}function ta(c){c.lb=!0;c.Ja=c.h.u();c.aa=c.h.o()}
function H(c){if(!c.s){var a=I.S();a&&"any"!==c.Qa&&Ga(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.u(),innerHeight:c.o()})}}async function Ha(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ia(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ja(c){return await self.C3_GetSvgImageSize(c.blob)}function Ka(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function La(c){self.setTimeout(()=>{c.kb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>Q(c,!0)),document.addEventListener("resume",()=>Q(c,!1))):document.addEventListener("visibilitychange",()=>Q(c,"hidden"===document.visibilityState));c.na=!("hidden"!==document.visibilityState&&!O);return{isSuspended:c.na}}
function Ma(c){c.jb||(c.jb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Na(c){c.ib||(c.ib=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Oa(c){await xa(c.url)}
function Pa(c,a){c.mb=a.message;-1===c.Ea&&(c.Ea=setTimeout(()=>{c.Ea=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.mb)},250))}function R(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:I.S(),innerWidth:c.u(),innerHeight:c.o()})}
function Q(c,a){c.na!==a&&((c.na=a)?c.h.Za():c.h.Ba(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.T()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Qa(c,a,b){"Backspace"===b.key&&M(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=wa.get(b.code)||b.code;p(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},J)}}
function S(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||p(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function T(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Ma);p(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},J);"mouse"===b.pointerType&&(c.Ma=
b.buttons)}}function V(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.C=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.C=a))}}
function Ra(c,a,b,d){const e=c.u(),f=c.o();c.N=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.S(),cssDisplayMode:c.h.wa()}):10>d&&Sa(c,e,f,d+1)}function Sa(c,a,b,d){-1!==c.N&&clearTimeout(c.N);c.N=setTimeout(()=>Ra(c,a,b,d),48)}
function Ga(c){c=c.Qa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ta(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
I.ga(class extends self.ua{constructor(c){super(c,"runtime");this.lb=!1;this.N=-1;this.Qa="any";this.na=this.ib=this.jb=!1;this.oa=document.createElement("div");this.oa.className="c3-screen-reader-text";this.oa.setAttribute("aria-live","polite");document.body.appendChild(this.oa);this.D=null;this.s=!1;this.mb="";this.Ea=-1;this.kb=!1;this.Ja=c.u();this.aa=c.o();this.C=this.da=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ha(b));c.i("runtime","raster-svg-image",b=>Ia(b));c.i("runtime","get-svg-image-size",b=>Ja(b));c.i("runtime","set-target-orientation",b=>{this.Qa=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ka(b));c.i("runtime","go-to-script",b=>Ka(b));c.i("runtime","before-start-ticking",()=>La(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var d=this.D;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.D&&(this.D.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ma(this));c.i("runtime","enable-device-motion",()=>Na(this));c.i("runtime","add-stylesheet",b=>Oa(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>{alert(b.message)});c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.oa.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+
b.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.h.ub().style.display="";this.h.Bb()});c.i("runtime","export-to-video-progress",b=>Pa(this,b));c.i("runtime","exported-to-video",b=>{window.ec({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.ec({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||
Aa(d)||b.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Ma=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.lb){var b=this.u();var d=this.o();if(this.h.Wa()){if(this.kb){if(this.Ja===
b&&d<this.aa){this.da=this.aa-d;V(this,this.aa,this.da);b=void 0;break a}0<this.da&&(this.da=0,V(this,d,this.da))}this.Ja=b;this.aa=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.S(),cssDisplayMode:this.h.wa()});this.h.T()&&(-1!==this.N&&clearTimeout(this.N),Ra(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",
()=>H(this));window.addEventListener("fullscreenerror",b=>R(this,b));window.addEventListener("webkitfullscreenerror",b=>R(this,b));window.addEventListener("mozfullscreenerror",b=>R(this,b));if(c.T()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.La=new Set;this.cc=new WeakSet;this.ac=!1}Ua(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,L)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},L);this.Ma=0});window.addEventListener("focusin",a=>{a=a.target;(Ba.has(a.tagName.toLowerCase())||Aa(a))&&m(this,"keyboard-blur",null,L)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("mousedown",a=>S(this,"mousedown",a,K));
window.addEventListener("mousemove",a=>S(this,"mousemove",a,K));window.addEventListener("mouseup",a=>S(this,"mouseup",a,K));window.addEventListener("dblclick",a=>S(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.C,pageX:a.pageX,pageY:a.pageY+this.C,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ta(a.target)&&
document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur();T(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{T(this,"pointermove",a)}):window.addEventListener("pointermove",a=>T(this,"pointermove",a));window.addEventListener("pointerup",a=>T(this,"pointerup",a));window.addEventListener("pointercancel",a=>T(this,"pointercancel",a));const c=()=>this.Aa();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.wb()&&!this.h.Wa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{V(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.T()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}u(){return this.h.u()}o(){return this.h.o()}Aa(){var c=
[...this.La];this.La.clear();if(!this.ac)for(const a of c)(c=a.play())&&c.catch(()=>{this.cc.has(a)||this.La.add(a)})}});"use strict";async function ra(c){if(c.$b)throw Error("already initialised");c.$b=!0;var a=c.B.za(("playable-ad"===c.B.g?c.B.M:"")+"dispatchworker.js");c.Da=await c.B.ta(a,c.W,{name:"DispatchWorker"});a=new MessageChannel;c.Ga=a.port1;c.Da.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Na=await va(c)}function sa(c){return[c.Ga,c.Na]}
async function va(c){const a=c.pb.length;var b=c.B.za(("playable-ad"===c.B.g?c.B.M:"")+"jobworker.js");b=await c.B.ta(b,c.W,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Da.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.pb.push(b);return e.port1}
self.zb=class{constructor(c){this.B=c;this.W=c.l;this.W="preview"===c.g?this.W+"workers/":this.W+c.M;this.bc=Math.min(navigator.hardwareConcurrency||2,16);this.Da=null;this.pb=[];this.Na=this.Ga=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.U({oc:!0,pc:"workermain.js",P:["scripts/c3runtime.js"],pa:[],Ta:"",lc:"scripts/",qa:[],sb:"html5"}));"use strict";
async function Ua(c,a){a=a.type;let b=!0;0===a?b=await Va():1===a&&(b=await Wa());m(c,"permission-result",{type:a,result:b})}async function Va(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Wa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.U.ga(class extends self.ua{constructor(c){super(c,"touch");q(this,"request-permission",a=>Ua(this,a))}});"use strict";function W(c){c.stopPropagation()}
self.U.ga(class extends self.ha{constructor(c){super(c,"button")}sa(c,a){const b=document.createElement("input");var d=b;a.isCheckbox?(b.type="checkbox",d=document.createElement("label"),d.appendChild(b),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):b.type="button";d.style.position="absolute";d.addEventListener("pointerdown",W);d.addEventListener("pointermove",
W);d.addEventListener("pointerrawupdate",W);d.addEventListener("pointerup",W);d.addEventListener("mousedown",W);d.addEventListener("mouseup",W);d.addEventListener("keydown",W);d.addEventListener("keyup",W);d.addEventListener("contextmenu",e=>e.preventDefault());b.addEventListener("click",()=>w(this,"click",c,{isChecked:b.checked}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.ja(d,a);return d}ya(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}ja(c,a){const b="input"===c.tagName.toLowerCase()?
c:c.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;c.title=a.title;c===b?b.value=a.text:c.lastChild.textContent=a.text}});"use strict";function Xa(c){c.replaceChildren?c.replaceChildren():c.innerHTML=""}
function X(c){c=Array.from(c.querySelectorAll("script:not([c3-executed])"));for(const b of c){c=b.parentNode;var a=c.replaceChild;const d=document.createElement("script");d.text=b.text;const e=b.attributes;for(let f=0,h=e.length;f<h;++f){const g=e[f];d.setAttribute(g.name,g.value)}d.setAttribute("c3-executed","");a.call(c,d,b)}}function Y(c,a,b){return a?b?Array.from(c.querySelectorAll(a)):(c=c.querySelector(a))?[c]:[]:[c]}
function Z(c){return c?{isOk:!0,html:c.innerHTML,text:c.textContent}:{isOk:!1}}
self.U.ga(class extends self.ha{constructor(c){super(c,"html-element");u(this,"set-content",(a,b)=>{{const e=b.str,f=b.type,h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)"html"===f?(k.innerHTML=e,X(k)):k.textContent=e;d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set content: ",g),d=Z(null)}}return d});u(this,"insert-content",(a,b)=>{{const e=b.str,f=b.type,h=b["at-end"]?"beforeend":"afterbegin",g=b.selector;b=b["is-all"];try{const k=
Y(a,g,b);if(0===k.length)var d=Z(null);else{for(const l of k)"html"===f?(l.insertAdjacentHTML(h,e),X(l)):l.insertAdjacentText(h,e);d=Z(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=Z(null)}}return d});u(this,"remove-content",(a,b)=>{{const e=b["is-clear"],f=b.selector;b=b["is-all"];if(f)try{const h=Y(a,f,b);if(0===h.length)var d=Z(null);else{for(const g of h)e?Xa(g):g.remove();d=Z(a)}}catch(h){console.warn("[HTML element] Failed to remove content: ",h),d=Z(null)}else Xa(a),
d=Z(a)}return d});u(this,"set-content-class",(a,b)=>{{const e=b.mode,f=b["class-array"],h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)for(const l of f)switch(e){case "add":k.classList.add(l);break;case "toggle":k.classList.toggle(l);break;case "remove":k.classList.remove(l)}d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set class: ",g),d=Z(null)}}return d});u(this,"set-content-attribute",(a,b)=>{{const e=b.mode,f=b.attribute,h=b.value,
g=b.selector;b=b["is-all"];try{const k=Y(a,g,b);if(0===k.length)var d=Z(null);else{for(const l of k)switch(e){case "set":l.setAttribute(f,h);break;case "remove":l.removeAttribute(f)}d=Z(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=Z(null)}}return d});u(this,"set-content-css-style",(a,b)=>{{const e=b.prop,f=b.value,h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set style: ",g),d=Z(null)}}return d});u(this,"get-element-box",(a,b)=>{(a=(b=b.selector)?a.querySelector(b):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});u(this,"insert-img-element",(a,b)=>{a:{const e=b.blobUrl;var d=b.width;const f=b.height,h=b.selector,g=b.insertAt;let k=a;if(h&&(k=a.querySelector(h),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;b.id&&(d.id=b.id);
b["class"]&&(d.className=b["class"]);0===g?k.prepend(d):1===g?k.append(d):k.replaceChildren?k.replaceChildren(d):(Xa(k),k.append(d));a=Z(a)}return a});u(this,"set-scroll-position",(a,b)=>{a:{const d=b.selector,e=b.direction;b=b.position;if(d&&(a=a.querySelector(d),!a)){b=void 0;break a}"left"===e?a.scrollLeft=b:a.scrollTop=b;b=void 0}return b})}sa(c,a){const b=document.createElement(a.tag);a["style-attribute"]&&b.setAttribute("style",a["style-attribute"]);b.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==b&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());b.addEventListener("pointerdown",e);b.addEventListener("pointermove",e);b.addEventListener("pointerrawupdate",e);b.addEventListener("pointerup",e);b.addEventListener("mousedown",e);b.addEventListener("mouseup",e);b.addEventListener("dblclick",e)}a["allow-context-menu"]&&b.addEventListener("contextmenu",e=>e.stopPropagation());b.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===b)break;e=e.parentNode}w(this,"click",c,{chain:f})});b.addEventListener("animationend",e=>{const f=e.target;w(this,"animationend",c,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(b.id=a.id);a.className&&(b.className=a.className);a["css-color"]&&(b.style.color=a["css-color"]);a["css-background-color"]&&(b.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(b.style.userSelect="none",b.style.webkitUserSelect="none");d=a.str;"html"===a.type?(b.innerHTML=d,X(b)):b.textContent=d;w(this,"initial-content",c,{html:b.innerHTML,text:b.textContent});return b}ja(c,a){c.innerHTML=a.html;X(c)}});
